contacts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('contacts/', views.contacts_list, name='contacts_list'),
    path('contacts/create/', views.create_contact, name='create_contact'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todos.urls', namespace='todos')),
    path('', include('contacts.urls', namespace='contacts')),
    
]

todos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('<int:category_id>/', views.todo_list, name='todo_list_by_category'),
    path('create/', views.create, name='create_todo'),
    # path('<int:todo_id>/', views.change_status, name='change_status'),
]

contacts/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100, blank=False, db_index=True)
    tel_number = models.CharField(max_length=12, blank=False, db_index=True)
    email = models.EmailField(blank=True)

    class Meta:
        ordering = ('name',)


    def __str__(self):
        return f'{self.name} - {self.tel_number}'

todos/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    description = models.CharField(max_length=200)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class ToDo(models.Model):
    category = models.ForeignKey(Category,
                                related_name='todos',
                                on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    completed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('id', 'completed')
        verbose_name = 'ToDo'
        verbose_name_plural = 'ToDos'

    def __str__(self):
        return self.title
    

contacts/forms.py
from django import forms
from .models import Contact


class ContactAddForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'tel_number', 'email']
        widgets = {
            'name': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 1
            }),
            'tel_number': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 1
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control'
            })
        }

todos/forms.py
from django import forms
from .models import ToDo


class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['title', 'description', 'category']
        widgets = {
            'title': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 1,
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'category': forms.Select(attrs={
                'class': 'form-control'
            })
        }

contacts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Contact
from .forms import ContactAddForm



def contacts_list(request):
    contacts = Contact.objects.all()
    return render(request, 'contacts_list.html', {'contacts': contacts})

def create_contact(request):
    form = ContactAddForm()
    if request.method == 'POST':
        form = ContactAddForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            contact = Contact(name=cd['name'],
                        tel_number=cd['tel_number'],
                        email=cd['email'])
            contact.save()
        return redirect('/contacts')

    return render(request, 'contacts/create_contact.html', {'create_form': form})

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, ToDo
from .forms import ToDoForm


# Create your views here.
def todo_list(request, category_id=None):
    category = None
    categories = Category.objects.all()
    todos = ToDo.objects.all()
    if request.method == 'POST':
        
        todo = get_object_or_404(ToDo, id=request.POST['todo_id'])
        todo.completed = not todo.completed
        todo.save()
        return redirect('/')
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        todos = todos.filter(category=category)
    return render(request, 'todos/todo_list.html',
                {'category': category,
                'categories': categories,
                'todos': todos})

def create(request):
    form = ToDoForm()
    if request.method == 'POST':
        form = ToDoForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            todo = ToDo(title=cd['title'],
                        description=cd['description'],
                        category=cd['category'])
            todo.save()
        return redirect('/')

    return render(request, 'todos/create.html', {'create_form': form})

contacts/templates/contacts/create_contact.html
{% extends "base.html" %}
{% block title %}Создать контакт{% endblock %}
{% block content %}
<div class="container">
    <form action="." method="POST">
        {% csrf_token %}
        {{ create_form.as_p }}
        <input type="submit" value="Создать">
        
    </form>
    
</div>
{% endblock %}

contacts/templates/contacts_list.html
{% extends "base.html" %}
{% block title %}Контакты{% endblock %}
{% block content %}
<div class="container">
    <table class="table">
        <thead>
          <tr>
            
            <th scope="col">Имя</th>
            <th scope="col">Телефон</th>
            <th scope="col">Email</th>
            
          </tr>
        </thead>
        <tbody>
            {% for contact in contacts %}
            
                    
                    <td>{{ contact.name }}</td>
                    <td>{{ contact.tel_number  }}</td>
                    <td>{{ contact.email }}</td>
                    
                </tr>
            
            {% endfor%}

        
        </tbody>
      </table>
</div>
</div>
{% endblock %}

todos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <title>{% block title %}Мои дела{% endblock %}</title>
    </head>
    <body>
        <div class="row">
            <div class="col-1">
                <div class="container">
                    {% include "includes/side_menu.html" %}
                </div>
            </div>
            <div class="col-11">
            <div class="container">
                <ul class="nav nav-pills nav-fill">
                    
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'todos:todo_list' %}">Дела</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'contacts:contacts_list' %}">Контакты</a>
                      </li>
                             
                  </ul>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

todos/templates/includes/side_menu.html
{% if todos %}
<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link{% if not category %} active{% endif %}" aria-current="page" href="{% url 'todos:todo_list' %}">Все дела</a>
    </li>
    {% for c in categories %}
    <li class="nav-item">
        <a class="nav-link{% if category.id == c.id %} active{% endif %}" href="/{{ c.id }}/">{{ c.name }}</a>
    </li>
    {% endfor %}

    <li class="nav-item">
        <a class="nav-link" href="{% url 'todos:create_todo' %}">Добавить</a>
    </li>      
</ul>
{% elif contacts%}
<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contacts:create_contact' %}">Добавить</a>
    </li>  
</ul>
{% endif %}

todos/templates/todos/create.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form action="." method="POST">
        {% csrf_token %}
        {{ create_form.as_p }}
        <input type="submit" value="Создать">
        
    </form>
    
</div>
{% endblock %}

todos/templates/todos/todo_list.html
{% extends 'base.html' %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Мои дела{% endif %}
{% endblock %}

{% block content %}

<div class="container">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Описание</th>
            <th scope="col">Категория</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
            <form action="." method="POST">
                {% csrf_token %}
                <input type="hidden" name="todo_id" value="{{ todo.id }}">
                <tr class="{% if todo.completed %}table-success{% else %}table-danger{% endif %}">
                    <th scope="row">{{ todo.id }}</th>
                    <td>{{ todo.title }}</td>
                    <td>{{ todo.description }}</td>
                    <td>{{ todo.category }}</td>
                    <td><button type="submit" class="btn btn-warning">{% if todo.completed %}Не выполнил{% else %}Выполнил{% endif %}</button></td>
                </tr>
            </form>
            {% endfor%}

        
        </tbody>
      </table>
</div>
</div>
{% endblock %}